import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Food from "@/components/Food";
import Courses from "@/components/Courses";
import { menuItems } from "@/data/courses";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Food />
        {menuItems.map((item, i) => {
          return (
            <div key={i}>
              <Courses {...item} />
            </div>
          );
        })}
      </body>
    </html>
  );
}
